// src/components/Home.vue
<template>
	<div class="container">
		<div>
			<h1 class="title">Healthcheck System</h1>
			<p>
				<img src="../assets/images/logo.png" border="0" alt="" class="logo"/>
			</p>
			<br/>
			<p>Welcome! Click on button below to open dashboard!</p>
			<br/>
			<br/>
			<p>
				<router-link to="/dashboard" class="button is-large">Dashboard</router-link>
			</p>
		</div>

		<br/>
		<br/>
		<br/>

		<div class="columns">
			<div class="column">
				<h4 class="subtitle is-4">Simple structure</h4>
				<p>With a file based structure you can easily versioning all files</p>
			</div>
			<div class="column">
				<h4 class="subtitle is-4">Simple API</h4>
				<p>It works with a simple API, using HTTP requests to make everything - if you want</p>
			</div>
			<div class="column">
				<h4 class="subtitle is-4">Friendly Interface</h4>
				<p>You can see your checks with a nice and friendly web responsive interface</p>
			</div>
		</div>

		<app-footer></app-footer>
	</div>
</template>

<script>
	import AppFooter from "./AppFooter";

	export default {
		components: {AppFooter},
		name: 'home',
		data () {
			return {}
		}
	}
</script>

<style scoped>
	.container {
		text-align: center;
	}

	.container h1 {
		margin-top: 80px;
	}

	.container .logo {
		height: 200px;
	}

	.columns {
		margin: 0;
	}
</style>

// src/app/components/home/home.component.ts
import { Component } from "@angular/core";

@Component({
	selector: 'home',
	templateUrl: 'home.component.html',
	styleUrls: ['home.component.css']
})

export class HomeComponent {
}

<div class="container">
	<div class="home-index">

		<div class="jumbotron">
			<h1>Healthcheck System</h1>

			<p class="lead">
				<img src="../../../static/images/logo.png" border="0" alt="" class="logo"/>
			</p>

			<p class="lead">Welcome! Click on button below to open dashboard!.</p>

			<p>
				<a class="btn btn-lg btn-default" routerLink="/dashboard" href="javascript: void(0);">Dashboard</a>
			</p>
		</div>

		<div class="body-content">

			<div class="row">
				<div class="col-lg-4">
					<h2>Simple structure</h2>
					<p>With a file based structure you can easily versioning all files</p>
				</div>
				<div class="col-lg-4">
					<h2>Simple API</h2>
					<p>It works with a simple API, using HTTP requests to make everything - if you want</p>
				</div>
				<div class="col-lg-4">
					<h2>Friendly Interface</h2>
					<p>You can see your checks with a nice and friendly web responsive interface</p>
				</div>
			</div>

		</div>
	</div>
</div>
