// src/components/AppHeader.vue
<template>
	<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
		<div class="navbar-brand">
			<router-link to="/" class="navbar-item">
				<img src="../assets/images/logo-header.png" alt="GoHC" style="margin-right: 10px;">
				GoHC
			</router-link>

			<span class="navbar-burger" v-on:click="toggleMenu()">
				<span></span>
				<span></span>
				<span></span>
			</span>
		</div>		

		<div class="navbar-end navbar-menu" v-bind:class="{ 'is-active': menuActive }">
			<router-link to="/healthcheck/list" class="navbar-item is-tab" v-on:click.native="closeMenu()">{{ hcCount }} healtchchecks</router-link>
			<router-link to="/dashboard" class="navbar-item is-tab" v-on:click.native="closeMenu()">Dashboard</router-link>
			<router-link to="/" class="navbar-item is-tab" v-on:click.native="closeMenu()">Home</router-link>
			<router-link to="/settings" class="navbar-item is-tab" v-on:click.native="closeMenu()">Settings</router-link>
			<router-link to="/about" class="navbar-item is-tab" v-on:click.native="closeMenu()">About</router-link>
		</div>
	</nav>
</template>

<script>
	export default {
		name: 'app-header',
		data () {
			return {
				menuActive: false
			}
		},
		methods: {
			toggleMenu() {
				this.menuActive = !this.menuActive;
			},
			closeMenu() {
				this.menuActive = false;
			}
		},
		computed: {
			hcCount () {
				return this.$store.getters.hcCount;
			}
		}
	}
</script>

<style scoped>
	.nav-left .nav-item img {
		margin-right: 10px;
	}
</style>

// src/app/components/app-header/app-header.component.ts
import { Component } from "@angular/core";
import { GlobalService } from "../../services/GlobalService";

@Component({
	selector: 'app-header',
	templateUrl: 'app-header.component.html',
	styleUrls: ['app-header.component.css']
})

export class AppHeaderComponent {

	hcCount: number = 0;

	constructor(private globalService: GlobalService) {
		globalService.hcCountEmitter.subscribe((count: number) => {
			this.hcCount = count;
		});
	}

}

<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapse"
					aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" routerLink="/home" href="javascript: void(0);">
				<img src="../../../static/images/logo-header.png" border="0" alt="" class="logo pull-left"/>
				GoHC
			</a>
		</div>
		<div id="nav-collapse" class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li>
					<a routerLink="/healthcheck/list" href="javascript: void(0);">
						<span>{{hcCount}}</span>
						<span>healthchecks</span>
					</a>
				</li>
				<li>
					<a routerLink="/dashboard" href="javascript: void(0);">Dashboard</a>
				</li>
				<li>
					<a routerLink="/home" href="javascript: void(0);">Home</a>
				</li>
				<li>
					<a routerLink="/system/settings" href="javascript: void(0);">Settings</a>
				</li>
				<li>
					<a routerLink="/about" href="javascript: void(0);">About</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
